import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/homepage/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { ViewTransitions } from "next-view-transitions";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session) {
    return redirect("/auth");
  }
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${inter.className} h-full`}>
          <div className="container mx-auto flex gap-5 h-full p-5">
            <Sidebar session={session} />
            <main className="flex-1 border-primary rounded-lg border-2 h-full p-4">
              {children}
            </main>
            <Toaster />
          </div>
        </body>
      </html>
    </ViewTransitions>
  );
}
